(setq org-agenda-custom-commands (quote (("w" todo "WAITING" nil) ("n" todo "NEXT" nil) ("d" "Agenda + Next Actions" ((agenda) (todo "NEXT"))))))
(setq org-agenda-files (quote ("~")))
(setq org-agenda-skip-deadline-if-done t)
(setq org-agenda-skip-scheduled-if-done t)
(setq org-agenda-sorting-strategy (quote ((agenda time-up priority-down tag-up) (todo tag-up))))
(setq org-agenda-time-grid (quote ((daily weekly today require-timed) #("----------------" 0 16 (org-heading t)) (800 1000 1200 1400 1600 1800 2000))))
(setq org-ascii-text-width 151)
(setq org-babel-ditaa-java-cmd "/usr/bin/ditaa")
(setq org-babel-load-languages (quote ((emacs-lisp . t) (python . t) (perl . t) (dot . t) (ditaa . t) (plantuml . t))))
(setq org-clock-out-remove-zero-time-clocks t)
(setq org-columns-default-format "%25ITEM %TODO %3PRIORITY %TAGS %Effort{:} %6CLOCKSUM{Total}")
(setq org-confirm-babel-evaluate nil)
(setq org-deadline-warning-days 7)
(setq org-ditaa-eps-jar-path "")
(setq org-ditaa-jar-option "")
(setq org-ditaa-jar-path "")
(setq org-export-backends (quote (ascii html icalendar latex odt confluence)))
(setq org-export-html-postamble t)
(setq org-export-html-postamble-format (quote (("en" "<p class=\"author\">Author: %a (%e)</p>
<p class=\"date\">Date: %d</p>
"))))
(setq org-export-html-style "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/org.css\" />")
(setq org-export-with-sub-superscripts (quote {}))
(setq org-from-is-user-regexp nil)
(setq org-global-properties (quote (("Effort_ALL" . "0:30 1:00 2:00 4:00 8:00 2d 3d 4d 5d 2w 1m"))))
(setq org-hide-leading-stars t)
(setq org-html-creator-string "")
(setq org-html-mathjax-options (quote ((path "./css/MathJax.js") (scale "100") (align "center") (indent "2em") (mathml nil))))
(setq org-log-done (quote time))

(setq org-refile-targets (quote ((org-agenda-files :maxlevel . 3))))
(setq org-src-fontify-natively t)
(setq org-src-tab-acts-natively t)
(setq org-startup-indented t)
(setq org-time-clocksum-use-effort-durations t)
(setq org-todo-keywords (quote ((type "TODO(t)" "MAYBE(m)" "WAITING" "NEXT(n)" "|" "DONE(d)"))))

(setq org-capture-templates
'(("t" "Short Todo" entry (file+headline "~/org/gtd.org" "Tasks") "* TODO %i\nAdded: %U")
   ("l" "Long Todo" entry (file+headline "~/org/gtd.org" "Tasks") "* TODO %^C\n    %i\nAdded: %U")
   ("m" "Mail Todo" entry (file+headline "~/org/gtd.org" "Tasks") "* TODO %:subject\n    %a\nAdded: %U")
   ("j" "Journal" entry (file+datetree "~/org/journal.org")
             "* %?\nEntered on %U\n  %i\n  %a"))
)
;; (setq org-default-notes-file (concat org-directory "~/notes.org"))
(setq org-startup-indented t)

(defun gtd ()
  (interactive)
  (find-file "~/org/gtd.org")
)

(provide 'org-settings)
